import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import { getPokemonList } from './api/service';

export default function Home() {
  const [pokemonList, setPokemonList] = useState([]);

  useEffect(() => {
    getPokemon();
  }, []);

  async function getPokemon() {
    const res = await getPokemonList();
    setPokemonList(res.results);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div data-testid='home-title'>Home</div>
        <ul data-testid='pokemon-list'>
          {pokemonList.map((value) => (
            <li key={value.url}>{value.name}</li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
