import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import PokemonDetails from './pokemon-details/[id]';

export default function Home() {
  const [pokemonName, setPokemonName] = useState('');

  function searchByPokemonName(event) {
    event.preventDefault();
    const formPokemonName: string = event.target.name.value;
    setPokemonName(formPokemonName.toLowerCase());
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div data-testid='home-title' className={styles.title}>
          Pokedex
        </div>
        <div data-testid='pokedex' className={styles.pokedexContainer}>
          <div className={styles.pokemonDetails}>
            <div className={styles.pokemonDetailsHeader}></div>
            <div data-testid='screen' className={styles.screen}>
              <PokemonDetails pokemonName={pokemonName} />
            </div>

            <div className={styles.pokemonDetailsFooter}></div>
          </div>
          <div className={styles.pokedexDivider}></div>
          <div className={styles.pokemonSearch}>
            <form className={styles.searchForm} onSubmit={searchByPokemonName}>
              <label htmlFor='name'>Pokemon Name</label>
              <input id='name' type='text' autoComplete='name' required />
              <button type='submit'>Search</button>
            </form>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
